name: API Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BASE_URL: https://data-api.solar-twin.dev
      AUTH_HEADER: ${{ secrets.SOLAR_TWIN_AUTH_HEADER }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: pytest -v
